name=yottaUI
version=0.1.0
author=Collin Barker
maintainer=Collin Barker
sentence=Screen Wrapper for Adafruit screens
paragraph=Screen wrapper for adafruit screens enabling easier draw and 2 screens on same spi bus
category=Screen control
url=https://github.com/97cweb/yottaUI
architectures=*
depends=adafruit_GFX
